#!/bin/sh
# Script to do any post-install system changes

PREFIX=${PKG_PREFIX-/usr/local}

if [ "$2" != "POST-INSTALL" ] ; then
   exit 0
fi

set +e

# If this is during staging, we can skip for now
echo $PREFIX | grep -q '/stage/'
if [ $? -eq 0 ] ; then
   exit 0
fi

# ---- SYSTEM OVERLAY FILES - KEEP THESE TO A MINIMUM!! ----
#Make sure the devfs.rules file is always overwritten with the Trident version 
# (a base package also overwrites this file regularly - we need more things enabled though)
cp /etc/devfs.rules.trident /etc/devfs.rules

#Overwrite the Linux printer test page with one
#  from the original CUPS 1.3 release from Apple (generic test images)
#cp ${PREFIX}/share/cups/data/default-testpage.orig.pdf ${PREFIX}/share/cups/data/default-testpage.pdf

# Run the service validation routine to ensure the system services are sane
${PREFIX}/share/trident/scripts/validate-services.sh ${PREFIX}/etc/trident/required-services ${PREFIX}/etc/trident/recommended-services

exit 0
