#!/bin/sh
# Script to do any post-install system changes

PREFIX=${PKG_PREFIX-/usr/local}

if [ "$2" != "POST-INSTALL" ] ; then
   exit 0
fi

set +e

# If this is during staging, we can skip for now
echo $PREFIX | grep -q '/stage/'
if [ $? -eq 0 ] ; then
   exit 0
fi
#Now make sure we account for alternate root dir for installation
if [ -z "${PKG_ROOTDIR}" ] ; then
	PKG_ROOTDIR=/
fi
PREFIX=${PKG_ROOTDIR}${PREFIX}

replace_if_default(){
  #INPUTS: 1: File to replace
  #        2: Default file from other package
  #        3: Trident File to replace with
  local replace=0
  if [ ! -e "$1" ] || [ ! -e "$2" ] ; then 
    replace=1
  else 
    cmp -s "${1}" "${2}"
    if [ $? != 1 ] ; then replace=1 ; fi
  fi
  if [ 1 -eq ${replace} ] && [ -e "${3}" ] ; then
    if [ -e "$1" ] ; then rm "${1}" ; fi
    #use a symlink so if the trident file changes, the system will follow (unless manually changed by user)
    ln -s "${3}" "${1}" 
  fi
}
# ---- SYSTEM OVERLAY FILES - KEEP THESE TO A MINIMUM!! ----
#Overwrite the Linux printer test page with one
#  from the original CUPS 1.3 release from Apple (generic test images)
#cp ${PREFIX}/share/cups/data/default-testpage.orig.pdf ${PREFIX}/share/cups/data/default-testpage.pdf

#Ensure that the trident pulseaudio config file replaces the default one from pulseaudio (does not work)
replace_if_default ${PREFIX}/etc/pulse/default.pa ${PREFIX}/etc/pulse/default.pa.sample ${PREFIX}/etc/pulse/default.pa.trident
#Ensure the PCDM config file is set to the Trident defaults
replace_if_default ${PREFIX}/etc/pcdm.conf ${PREFIX}/etc/pcdm.conf.dist ${PREFIX}/etc/pcdm.conf.trident
#Ensure the Lumina config file is set to the Trident defaults
replace_if_default ${PREFIX}/etc/luminaDesktop.conf ${PREFIX}/etc/luminaDesktop.conf ${PREFIX}/etc/luminaDesktop.conf.trident
#Other configuration file replacements
# ALSA config file
replace_if_default ${PREFIX}/etc/asound.conf ${PREFIX}/etc/asound.conf.sample ${PREFIX}/etc/asound.conf.trident
replace_if_default ${PREFIX}/etc/openal/alsoft.conf ${PREFIX}/etc/openal/alsoft.conf.sample $${PREFIX}/etc/openal/alsoft.conf.trident

# Run the service validation routine to ensure the system services are sane
${PREFIX}/share/trident/scripts/validate-services.sh ${PREFIX}/etc/trident/required-services ${PREFIX}/etc/trident/recommended-services

exit 0
