#!/bin/sh
# Copyright (c) 2015 Kris Moore (iXsystems / PC-BSD)
# License: BSD

## System variables. DO NOT CHANGE
LOGFILE="/var/log/trident-tor.log"

test -e /sbin/rc-update
use_openrc=$?

if use_openrc ; then
  fw_service="ipfw"
else
  fw_service="firewall"
fi

## Set up our logging
## Redirect Output to a logfile and screen
exec 3>&1                         # create pipe (copy of stdout)
exec 1>$LOGFILE                   # direct stdout to file
#exec 2>&1                         # uncomment if you want stderr too

## Only privileged user can run this.
if [ ! `id -u` == "0" ]; then
  echo "Permission Denied: You need to run this command as root or as a privileged user!"
  exit 1
else
  ## Stop Tor service
  service tor status
  if [ $? -eq 3 ]; then
    echo " "
    echo "Service Tor has already been stopped or did not start"
  else
    service tor stop
  fi
  
  ## Stop socat service
  service socat status
  if [ $? -eq 3 ]; then
    echo " "
    echo "Service socat has already been stopped or did not start"
  else
    service socat stop
  fi
  
  ## Turn off the special config options for the firewall and socat
  sysrc -f /etc/rc.conf -x firewall_script
  #sysrc -f /etc/rc.conf -x firewall_coscripts
  sysrc -f /etc/rc.conf -x socat_flags
  sysrc -f /etc/rc.conf -x tor_conf
  sysrc -f /etc/rc.conf -x tor_pidfile
  sysrc -f /etc/rc.conf -x tor_datadir
  
  ## Return dhclient.conf settings to what it was before
  if [ -e "/etc/dhclient.conf.preTor" ]; then
    mv /etc/dhclient.conf.preTor /etc/dhclient.conf
  fi

  ## Return DNS settings to what it was before
  if [ -e "/etc/resolv.conf.preTor" ]; then
    mv /etc/resolv.conf.preTor /etc/resolv.conf
  fi
  
  ## Return sysctl.conf file to what it was before.
  if [ `sysctl -n net.inet.ip.random_id` == "1" ]; then
    sysctl net.inet.ip.random_id=0
  fi
  rm /etc/sysctl.d/tor-mode.conf
  
  ## Let's restart the firewall
  service "${fw_service}" restart
  
  exit 0
fi
