#!/bin/bash
if [ -e "/var/service/docker" ] ; then
  # Remove dangling docker images periodically
  # will not impact docker "users" very much,
  # but indespensible for docker builders
  docker image prune -f
fi
