#!/bin/bash
if [ -e "/usr/bin/zfs-prune-snapshots" ] ; then

  #Docker snapshots (docker build can create tons of these - does not always cleanup later)
  dockerds=$(mount | grep " on /var/lib/docker " | cut -d " " -f 1)
  zfs-prune-snapshots 1w ${dockerds} > /var/log/cron/prune-snapshots.log 2>&1

fi
